apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: my-node-app
        image: dockernode27.azurecr.io/dockernode:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
